telegram_bot:
  token: 2016597456:AAFKlN3ASwM6_05tccyv0qYBygCLFGIOxHY

vk:
  token: c2198bf65b1927328d6fafb49f77b4d666a8f51e8d7e2b0c0da076e2359b1865bcd20367cff7bee2746fc

instagram:
  sessionid: 49574997587%3AS8TTgxXImqwQpl%3A18

yoomoney:
  access_token: 4100117220801820.13D00DCE6B299A10981A50772534493C088F476B045D766507C78B21A43D0DA771B6E073E918DF8600166CF462B4CA281585CCFA6A1BF1C1B01FBB51AE6CC166B6ED032D1E397D2BB58EF7DB828A9FD6AC8B299F7A23F69BF9E34D803F7B5CCF5705CB5BDC227AA3890359656130B08DED37D88319FDA8B365671A6137991379
  client_id: 9D0197D576DC35B3558741E3AFF13AC97BF519F456B057D1DF1C76A3F3ACD73D
  redirect_uri: https://t.me/dada_ptizza_tg_bot
  scope: account-info operation-history incoming-transfers

hacks:
  -
    id: '1'
    blur: [
      'AgACAgIAAxkDAAIFCGF0Q6QEogonnAZscep7VDscZeUJAAKKuDEbS6ehS25Py_wVqXrwAQADAgADcwADIQQ',
      'AgACAgIAAxkDAAIFCWF0Q6XtCL8_0oB5FxoW8cbeGHSfAAI2uTEbS6ehS5K8ixwtvobIAQADAgADcwADIQQ',
    ]
    orig: [
      'AgACAgIAAxkDAAIFCmF0Q6WWCmtMR0b7lZhgiE7Xmu1sAAJtuDEbS6ehSzYeh5hXWYy7AQADAgADcwADIQQ',
      'AgACAgIAAxkDAAIFC2F0Q6UjIgS3fcBH8T_mtIswUlBLAAJuuDEbS6ehS2KlSlmrwa60AQADAgADcwADIQQ',
    ]

  -
    id: '2'
    blur: [
      'AgACAgIAAxkDAAIFDGF0Q6VWcrAizQEH-ouLLjmyIBWAAAI3uTEbS6ehS8t3JsXQsoc3AQADAgADcwADIQQ',
      'AgACAgIAAxkDAAIFDWF0Q6ZA2i9NvGB6Y_UsvzsdNZDGAAKKuDEbS6ehS25Py_wVqXrwAQADAgADcwADIQQ',
      'AgACAgIAAxkDAAIFDmF0Q6Zj9bEUc0i6ofwZLrqhNW-LAAI2uTEbS6ehS5K8ixwtvobIAQADAgADcwADIQQ',
    ]
    orig: [
      'AgACAgIAAxkDAAIFD2F0Q6ZE3h55IdG6TvSubIh9EFi_AAJwuTEbS6ehS1A_VfO8xLBjAQADAgADcwADIQQ',
      'AgACAgIAAxkDAAIFEGF0Q6esqCUiJcMFLkGXC4MqLrGLAAJtuDEbS6ehSzYeh5hXWYy7AQADAgADcwADIQQ',
      'AgACAgIAAxkDAAIFEWF0Q6c9AzhBUMAOQR1b5ZFiAgOdAAJuuDEbS6ehS2KlSlmrwa60AQADAgADcwADIQQ'
    ]

  -
    id: '3'
    blur: [
      'AgACAgIAAxkDAAIFEmF0Q6c2j5tcKjEMnDSjTe2gn4SCAAKKuDEbS6ehS25Py_wVqXrwAQADAgADcwADIQQ',
      'AgACAgIAAxkDAAIFE2F0Q6cl3-mGQvnFFfFRIkVMK-XRAAI4uTEbS6ehS299sWNkywr4AQADAgADcwADIQQ',
    ]
    orig: [
      'AgACAgIAAxkDAAIFFGF0Q6goioh7bGHi6nlEdyrIfkjdAAJuuDEbS6ehS2KlSlmrwa60AQADAgADcwADIQQ',
      'AgACAgIAAxkDAAIFFWF0Q6hodATH3XNdP6Y14mJJIXKPAAI5uTEbS6ehS1P3riekX8hMAQADAgADcwADIQQ',
    ]